baseURL = 'https://drtim101.github.io/'
languageCode = 'en-uk'
title = "DrTim 101"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = "Ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "DrTim 101"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages
